#:schema node_modules/wrangler/config-schema.json
name = "blue-tree-81ae"
compatibility_date = "2025-08-14"
main = "src/app.py"
compatibility_flags = ["python_workers"]


[ai]
binding = "AI"

[[d1_databases]]
binding = "Stock"
database_name = "Stock"
database_id = "00fe33e0-509c-4743-a420-d16823905f22"
